#!/usr/bin/python3

import dbus
import sys


def check_wifi(manager):
	properties = manager.GetProperties()
	print("wifi is: %s" % properties["Powered"])
	return properties["Powered"]

def set_wifi(manager, enabled):
	print("wifi set to", enabled)
	wifi_powered = manager.SetProperty("Powered", enabled)
	print("wifi set error: %s" % wifi_powered)

if __name__ == "__main__":

	num_args = len(sys.argv)

	if (num_args == 1 or sys.argv[1] == "flip"):
		check = True
	elif (num_args == 2):
		check = False
	else:
		print("Usage: %s  0|1|flip" % (sys.argv[0]))
		exit(1)

	bus = dbus.SystemBus()
	manager = dbus.Interface(bus.get_object('net.connman','/net/connman/technology/wifi'),'net.connman.Technology')

	if check == True:
		current = check_wifi(manager)
		if num_args == 2 and sys.argv[1] == "flip":
			set_wifi(manager, not bool(current))
	else:
		set_wifi(manager, int(sys.argv[1]) > 0)
